# Generated by Django 2.2.8 on 2021-06-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=32)),
                ('company', models.CharField(max_length=32)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
