# Generated by Django 2.2.8 on 2021-06-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinformation',
            name='category',
            field=models.CharField(choices=[('Electronincs', 'Electronincs'), ('Clothing', 'Clothing'), ('Cosmetics', 'Cosmetics'), ('Stationary', 'Stationary'), ('Sports', 'Sports')], max_length=32),
        ),
    ]
